name: ReactDeployCI
on:
  push:
    branches:
      - react
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check dir
        run: ls
      - name: Install Packages
        run: cd h2hsite-react && npm install
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
      - name: Updating Domain
        run: echo "Update domain"
