name: ReactDeployCI
on:
  push:
    branches:
      - react
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: cd h2hsite-react && npm install
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: react-build # The branch the action should deploy to.
          FOLDER: h2hsite-react/build # The folder the action should deploy.
      - name: Updating Domain
        run: echo "Update domain"
